// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Models;

namespace webapi.Migrations
{
    [DbContext(typeof(VezbanjeContext))]
    [Migration("20210901174619_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("webapi.Models.Dan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Naziv");

                    b.Property<int?>("NedeljaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NedeljaID");

                    b.ToTable("Dani");
                });

            modelBuilder.Entity("webapi.Models.Nedelja", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ime");

                    b.HasKey("ID");

                    b.ToTable("Vezbanje");
                });

            modelBuilder.Entity("webapi.Models.Vezba", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Boja")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Boja");

                    b.Property<int?>("DanID")
                        .HasColumnType("int");

                    b.Property<string>("Workout")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Workout");

                    b.HasKey("ID");

                    b.HasIndex("DanID");

                    b.ToTable("Vezbe");
                });

            modelBuilder.Entity("webapi.Models.Dan", b =>
                {
                    b.HasOne("webapi.Models.Nedelja", "Nedelja")
                        .WithMany("Dani")
                        .HasForeignKey("NedeljaID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Nedelja");
                });

            modelBuilder.Entity("webapi.Models.Vezba", b =>
                {
                    b.HasOne("webapi.Models.Dan", "Dan")
                        .WithMany("Vezbe")
                        .HasForeignKey("DanID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Dan");
                });

            modelBuilder.Entity("webapi.Models.Dan", b =>
                {
                    b.Navigation("Vezbe");
                });

            modelBuilder.Entity("webapi.Models.Nedelja", b =>
                {
                    b.Navigation("Dani");
                });
#pragma warning restore 612, 618
        }
    }
}
